### ISSUE TITLE
Guzzle 3 is deprecated

### ISSUE THREAD

**Issue by russ-ab** [thunderpush/php-thunderclient#3]
Installed today via composer

```
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing symfony/event-dispatcher (v2.7.6)
    Downloading: 100%         

  - Installing guzzle/guzzle (v3.9.3)
    Downloading: 100%         

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
guzzle/guzzle suggests installing guzzlehttp/guzzle
    (Guzzle 5 has moved to a new package name. 
    The package you have installed, Guzzle 3, is deprecated.)

Writing lock file
Generating autoload files
```

They are planning to remove the repository soon

```
Guzzle 3 is only maintained for bug and security fixes. 
Guzzle 3 will be EOL at some point in late 2015.
```
Source: https://github.com/guzzle/guzzle3

Is there any plans to upgrade to guzzle5? It is a problem for who use the php client?

**Comment by russ-ab** [comment]
Cant make it work!

Steps I did:

1 - Clone repo 
2 - Composer install
3 - Create a file with example from readme

Got a blank screen

4 - Added error reporting to example
5 - Got the error:

```
( ! ) Fatal error: Class 'Guzzle\Http\Client' not found in /var/www/html/thunderpush/php-thunderclient/thunderclient/Thunder.php on line 32
Call Stack
#	Time	Memory	Function	Location
1	0.1198	241864	{main}( )	.../example.php:0
2	0.1211	255552	Thunder->__construct( ???, ???, ???, ???, ??? )	.../example.php:8
```

This is related to guzzle3 has been discontinued?

**Comment by pieterclaerhout** [comment]
+1

**Comment by kjagiello** [comment]
I have just pushed a commit that upgrades us to guzzle 6. It forces us however to drop support for PHP < 5.5. I am not sure how much of deal breaker it is? What versions are you guys running? (I have not touched a single line of PHP in a couple of years, so I'm not really up to date with the PHP world, so please bear with me ✌)

I have also stumbled into problems with running CI tests using PHP 5.5. For some reason, `phpunit` won't run on 5.5 after upgrading guzzle to version 6. Let me know if you have any ideas why it is not working like expected.

**Comment by pieterclaerhout** [comment]
Hmm, I'm still stuck on PHP 5.4 for the moment...

**Comment by kjagiello** [comment]
I've just released a new version (1.1.0) that uses guzzle5 and supports PHP 5.4. The version that uses guzzle6 is now available in a separate branch.

**Comment by pieterclaerhout** [comment]
Thanks for that!

**Comment by russ-ab** [comment]
Nice! Thanks man!

**Comment by kjagiello** [comment]
:beers:
